
[minion_calculations]
	"_example:_enchanted_coal,_diamond" = {}

	[minion_calculations.item]
		minion_drop = "ENCHANTED_COAL"

	[minion_calculations.profit_type]
		insta_sell = false
		insta_buy = false

[trackers]

	[trackers.skills]
		skill_tracker = false

	[trackers.aliases]
		skill_alias = "s"
		powder_alias = "powd"

	[trackers.reminder]
		remind_me = false

	[trackers.dailies]
		track_dailies = true
		track_capsaicin_eyerops = true
		visitor_cooldown = "720"
		track_century_cake = true
		track_garden_visitors = true
		track_matriarch_perfume = false
		track_hiker = false
		display_timers = true
		track_caducous_feeder = false
		track_capsaicin_eyedrops = true

	[trackers._bestiary]
		bestiary = false

[nether]

	[nether.kuudra]
		reparty_partner = "lhxseven"
		ping_offset = "0"
		kuudra_profit = false
		kuudra_reparty = false

[slayer]

	[slayer.slayer_calculations]
		slayer_cost = "3"
		magic_find = "390"
		kills_per_hour = "150"

	[slayer.eman_slayer]
		enchant_rune = "14000000"
		exceedingly_rare_ender_artifact_upgrader = "9700000"
		endersnake_rune = "20000"
		judgement_core = "320000000"
		end_rune = "950000"
		sinful_dice = "30000"
		void_conqueror_enderman_skin = "350000"
		pocket_espresso_machine = "300000"
		handy_blood_chalice = "2000000"
		etherwarp_merger = "400000"

	[slayer.revenant_slayer]
		beheaded_horror = "30000"
		pestilence_rune = "3000"
		snake_rune = "40000"
		shard_of_the_shredded = "16000000"
		warden_heart = "145000000"
		scythe_blade = "40000"

	[slayer.sven_slayer]
		red_claw_egg = "120000"
		couture_rune = "120000"
		overflux_capacitator = "97000000"
		grizzly_bait = "350000"

	[slayer.blaze_slayer]
		archfiend_dice = "7000000"
		mana_disintegrator = "1000000"
		"wilson's_engineering_plans" = "8000000"
		lavatears_rune = "750000"
		fiery_burst_rune = "3000000"
		high_class_archfiend_dice = "44000000"

	[slayer.time]
		total_kill_time = false

	[slayer.slayer_specifics]
		slayer_cost = "23750"
		magic_find = "289"
		kills_per_hour = "140"

	[slayer.tarantula_slayer]
		digested_mosquito = "500000"
		tarantula_talismen = "2000000"
		bite_rune = "40000"
		spirit_rune = "10000"

	[slayer.magic_find]
		magic_find = "290"

[minion_data]

	[minion_data.minion_10]
		minion_10_amount = "0"
		minion_10_speed = "0"

	[minion_data.minion_11]
		minion_11_amount = "0"
		minion_11_speed = "0"

	[minion_data.minion_12]
		minion_12_amount = "0"
		minion_12_speed = "0"

	[minion_data.minion_loot]
		insta_sell = false
		insta_buy = true
		minion_drop = "ENCHANTED_COAL"

	[minion_data.calculate_loot]
		insta_sell = false
		insta_buy = false
		sell_offer = false
		minion_drop = ""

	[minion_data.minion_9]
		minion_9_speed = "0"
		minion_9_amount = "0"

	[minion_data.minion_8]
		minion_8_speed = "0"
		minion_8_amount = "0"

	[minion_data.minions_12]
		minion_12_amount = "0"
		minion_12_speed = "0"

	[minion_data.minion_7]
		minion_7_speed = "0"
		minion_7_amount = "0"

	[minion_data.minions_11]
		minion_11_amount = "0"
		minion_11_speed = "0"

	[minion_data.minion_6]
		minion_6_speed = "0"
		minion_6_amount = "0"

	[minion_data.minions_10]
		minion_10_amount = "0"
		minion_10_speed = "0"

	[minion_data.minion_5]
		minion_5_amount = "0"
		minion_5_speed = "0"

	[minion_data.minion_4]
		minion_4_speed = "13.9"
		minion_4_amount = "1"

	[minion_data.minion_3]
		minion_3_speed = "12.9"
		minion_3_amount = "19"

	[minion_data.minion_2]
		minion_2_amount = "7"
		minion_2_speed = "12.4"

	[minion_data.minion_1]
		minion_1_amount = "5"
		minion_1_speed = "12"

	[minion_data."/ah_prices"]
		hydra_heads = ".5"
		gabagool_the_fish = "50"
		apex = "2.4"

[minion_speeds]

	[minion_speeds.pets]
		pet_speed = "0"

	[minion_speeds.minion_upgrade_slots]
		minion_expander = "0"
		fly_catcher = "2"

	[minion_speeds.minion_count]
		number_of_minions = "31"

	[minion_speeds.beacons_and_infusions]
		regular_power_crystal = "0"
		scorched_power_crystal = "1"
		minion_infusion = "1"

	[minion_speeds.item_calculations]
		t3_version = "15"
		t2_version = "160"

	[minion_speeds.minion_fuel]
		foul_flesh = "0"
		magma_bucket = "0"
		eternal_flame = "0"
		hyper_catalyst = "1"
		plasma_bucket = "0"
		lava_bucket = "0"
		hamster_wheel = "0"

	[minion_speeds.inferno_minion_fuel]
		amount_of_inferno_minions = "10"
		hypergolic_gabagool = "0"
		fuel_gabagool = "0"
		heavy_gabagool = "0"

[minion_calc]

	[minion_calc.item]
		minion_drop = "HEMOVIBE"

	[minion_calc.profit_type]
		insta_sell = false
		insta_buy = false

[minions_data]

	[minions_data.minion_10]
		minion_10_amount = "0"
		minion_10_speed = "0"

	[minions_data.minion_11]
		minion_11_amount = "0"
		minion_11_speed = "0"

	[minions_data.minion_12]
		minion_12_amount = "0"
		minion_12_speed = "0"

[economy]

	[economy.item_cost]
		display_raw_craft_cost = true

	[economy.auto]
		auto_check_prices = false

	[economy.search_loop]
		item_price = "2"
		auction_item_search_loop = false
		item_name = "Enchanted Book Bundle"
		loop_time = "66"
		item_lore = "Quantum"

	[economy.loop_timer]
		loop_time = "66"

	[economy.notifications]
		bazaar_notifier_timer = "10"
		bazaar = false

[slayer_calc]

	[slayer_calc.revenant_slayer]
		beheaded_horror = "30000"
		pestilence_rune = "3000"
		snake_rune = "40000"
		shard_of_the_shredded = "16000000"
		warden_heart = "145000000"
		scythe_blade = "40000"

	[slayer_calc.eman_slayer]
		enchant_rune = "14000000"
		exceedingly_rare_ender_artifact_upgrader = "9700000"
		endersnake_rune = "20000"
		judgement_core = "320000000"
		end_rune = "950000"
		sinful_dice = "30000"
		void_conqueror_enderman_skin = "350000"
		pocket_espresso_machine = "300000"
		handy_blood_chalice = "2000000"
		etherwarp_merger = "400000"

	[slayer_calc.sven_slayer]
		red_claw_egg = "120000"
		couture_rune = "120000"
		overflux_capacitator = "97000000"
		grizzly_bait = "350000"

	[slayer_calc.blaze_slayer]
		archfiend_dice = "7000000"
		mana_disintegrator = "1000000"
		"wilson's_engineering_plans" = "8000000"
		lavatears_rune = "750000"
		fiery_burst_rune = "3000000"
		high_class_archfiend_dice = "44000000"

	[slayer_calc.slayer_specifics]
		slayer_cost = "150000"
		magic_find = "320"
		kills_per_hour = "25"

	[slayer_calc.tarantula_slayer]
		digested_mosquito = "500000"
		tarantula_talismen = "2000000"
		bite_rune = "40000"
		spirit_rune = "10000"

[dungeon]

	[dungeon.dungeon_rejoin]
		player_1 = "somxone"
		rejoin_dungeon = false
		offset_ping = "500"
		normal = true
		player_4 = "volcaronitee"
		master_mode = false
		ping_offset = "0"
		player_3 = "epicslender"
		turn_on_auto_rejoin = false
		join_garden = true
		player_2 = "hutayo"
		dungeon_floor = "6"

	[dungeon.limbo]
		get_out_of_limbo = true

	[dungeon.party]
		party_commands = true

[auction]

	[auction.auction_search_loop]
		hydra_head = "2"
		item_price = "1.3"
		hydra_head_loop = true
		auction_item_search_loop = false
		item_name = "Enchanted Book Bundle"
		item_lore = "Quant"

	[auction.loop_timer]
		loop_time = "66"

[qol]

	[qol.item_timer]
		item_action_name = "Fire Veil"
		item_duration = "5"
		show_item_timer = false

	[qol.combat]
		broken_hyperion = false
		vanquisher_auto-warp = ""
		kuudra_reparty = ""

	[qol.commands]
		persistant_command = "pickupstash"
		time_loop = "3"

	[qol.wip]
		vanquisher_auto-warp = ""
		kuudra_reparty = ""

[minion_return]

	[minion_return.minion]
		current_minion = "7"
		desired_minion_upgrade = "9"

[rift]

	[rift.effigy]
		x-coordinate_offset = "0"
		effigy_timer = false
		y-coordinate_offset = "0"

	[rift.vampire_slayer]
		x-coordinate_offset = "225"
		y-scale = "2"
		test_health = true
		show_twin_claw_timer = false
		x-scale = "2"
		y-coordinate_offset = "50"

	[rift.blood_ichor]
		x_coordinate = "200"
		y-scale = "2"
		show_blood_ichor_timer = false
		x-scale = "2"
		y_coordinate = "100"

	[rift.vampire]
		vampire_slayer = false
		effigy_timer = false

	[rift.gui]
		x-coordinate = "0"
		y-coordinate = "0"

	[rift.twin_claw]
		x_coordinate = "200"
		x-coordinate_offset = "200"
		y-scale = "2"
		show_twin_claw_timer = false
		x-scale = "2"
		y-coordinate_offset = "50"
		y_coordinate = "200"

	[rift.vampire_execute]
		vampire_excute = false
		x-coordinate_offset = "200"
		y-scale = "2"
		x-coordinate = "225"
		vamp_max_health = "3000"
		y-coordinate = "20"
		test_health = true
		x-scale = "2"
		y-coordinate_offset = "20"

[kuudra]

	[kuudra.reparty]
		reparty_partner = ""
		ping_offset = "0"
		kuudra_reparty = false

[farming]

	[farming.crops]
		cocoa_beans = "600000"
		sugar_cane = "450000"
		potato = "1000000"
		cactus = "657000"
		nether_wart = "660000"
		wheat = "280000"
		melon = "1200000"
		pumpkin = "230000"
		mushroom = "450000"
		carrot = "1000000"

[daily]

	[daily.daily]
		track_dailies = true
		display_timers = true

[garden]

	[garden.visitors]
		visitor_profit = true
		copper_to_coin_ratio = "8"

	[garden.composter]
		composter_cost_reduction = "25"
		composter_speed = "25"
		composter_multi_drop = "25"

[bazaar]

	[bazaar.notifications]
		bazaar_notifier_timer = "30"
		bazaar = false

[party]

	[party.dungeon_reparty]
		dungeon_reparty = "rat"
		reparty = false

	[party.auto_join]
		party_auto_join_anyone = false
		party_auto_join_list_only = true
		party_auto_join_dungeon_leader_only = false

	[party.party]
		custom_party_message = ""
		party_commands = true
		custom_party_name = ""

[statistics]

	[statistics.division]
		numerator = "3348.9"
		denominator = "12588"

	[statistics.binomial_distribution]
		number_of_tries = "210"
		amount_of_times_dropped = "44"
		probability_of_the_drop = "0.26603908484270733"

